export const subscriptions = [
    {
        id: 1,
        name: "Plan Bonsai",
        img: "",
        price: "$149",
        duration: "por mes",
        color: "#34C759",
        includes: ["Semilla para un árbol", "Etiqueta en árbol", "Geolocalización", "Tips de cuidado"],
        link: "https://buy.stripe.com/test_cN20156ri9PAcj68ww",
    },
    {
        id: 2,
        name: "Plan Olmo",
        img: "",
        price: "$415",
        duration: "por seis meses",
        color: "#007AFF",
        includes: ["Semilla para un árbol", "Etiqueta en árbol", "Geolocalización", "Tips de cuidado"],
        link: "https://buy.stripe.com/test_cN20156ri9PAcj68ww",
    },
    {
        id: 3,
        name: "Plan Pinos",
        img: "",
        price: "$1500",
        duration: "por año",
        color: "#FF9500",
        includes: ["Semilla para un árbol", "Etiqueta en árbol", "Geolocalización", "Tips de cuidado"],
        link: "https://buy.stripe.com/test_cN20156ri9PAcj68ww",
    },
]